### ISSUE TITLE
replace Jest with spring-data-elasticsearch

### ISSUE THREAD

**Issue by bclozel** [spring-io/sagan#428]

**Comment by hanleijun** [comment]
no comment?

**Comment by bclozel** [comment]
Right now, I'm not very happy with the amount of code required for search features, and this part of the codebase is blocking some other parts of the roadmap.

I'm not saying Jest is bad, I'm just considering spring-data-elasticsearch as a replacement and my initial tests seem to support that.

Anything you'd like to know about this?

**Comment by bclozel** [comment]
actually this is not possible, as spring-data-elasticsearch supports the node and transport clients (the native ones), whereas PWS marketplace services only support the REST HTTP interface.

We have to stick to Jest, then.

**Comment by ptahchiev** [comment]
It seems like it's in their roadmap, however they don't know when it will be available. http://support.searchly.com/customer/en/portal/questions/15284142-spring-data-elasticsearch-and-searchly

**Comment by cforce** [comment]
+1 Spring data es support is mandatory. If PCF/PWS does not support the Spring way, you will loose the community soon. PWS is also missing a marketplace entry for the Spring Cloud Netflix services, that's another reason i am start asking me "Why shall i don't switch to another PAAS/SAAS platform than PWS if their don support their own stuff First citizen. Its really sad ;/

**Comment by bclozel** [comment]
Hi @cforce 

I don't think Spring Data ES is "mandatory" here. Of course our goal here is to have a real-world application using Spring technologies, but we certainly don't want to use any Spring project if it doesn't make sense for this use case.

At that point and judging from the type of queries we're making to the index, I'm not even sure Spring Data ES would be the obvious choice. I'd have to test things and think about it.

Now Spring Data ElasticSearch is a community-lead project and even though this is a feature requested a lot by the community, this has strong implications on the project itself. If this feature is really important to you, you can [help out on the dedicated issue, basically providing an ElasticsearchOperations implementation using Jest](https://jira.spring.io/browse/DATAES-220).

Now I'm not aware of a SaaS out there supporting ES with the native protocol (see the link provided by Petar on why this is harder than it seems). I guess it should be possible to create your marketplace service in PCF for this particular use case.

**Comment by cforce** [comment]
Jest is integrated, i am testing right now:
 https://github.com/cforce/spring-data-elasticsearch/tree/DATAES-220

**Comment by spring-operator** [comment]
it's easy enough to use ElasticCloud from PWS, as they're both hosted on
AWS, ultimately. Just create a user-provided-service and point to it. One
thing I'd love to see is Elastic Cloud supporting logstash so that
cloud-apps can also talk to it via syslogd:// drains for logs, but alas,
not yet :(

Also, PWS *does* support Netflix services. There are even binders on
start.spring.io for the PWS/PCF-based services (e.g.: search "Config
Server" in the drop down and you'll see a PWS/PCF-specific variant)

**Comment by spring-operator** [comment]
Um.

Wow. Literally everything I said in that last post is wrong. I'm so sorry I
misled you.

I could've *sworn* that Spring Cloud Services used to be there! I'm
inquiring as to what I did to think that and why they don't show up when i
do `cf marketplace`.

Elastic Cloud *doesn't* yet work with PWS because it requires a proprietary
authentication mechanism. I worked with ElasticSearch a month ago to sort
this issue out and thought it'd been fixed but apparently it's only gotten
as far as them granting a license to the Spring Data Elastic Search
developers to make it easy to fix, bt not fixed yet.

So, please feel free to ignore me. I'm clearly useless :(

**Comment by cforce** [comment]
One could deploy Spring Cloud Netflix Services hisself manually to PWS, however that's not how i expect Pivotal "eats their own dogfood"
