### ISSUE TITLE
Invalid blog anchors

### ISSUE THREAD

**Issue by olivergierke** [spring-io/sagan#492]
It's cool that the intermediate headlines in blog posts now display the anchors on hovering over them. However, the links created are not working in terms of that the anchor does not actually point to an existing element:

```html
<a name="user-content-projections-in-spring-data-rest" 
   class="anchor"
   href="#projections-in-spring-data-rest">
  …
</a>
```

See that the name of the anchor is prefixed with `user-content-` but the `href`-attribute points to the non-prefixed version.

**Comment by bclozel** [comment]
Hi @olivergierke 

I just edited this draft and saved it again - thus triggering the new engine and saving the new rendered version in database. It's now fine.

I think this bug actually happens because the rendered version saved in database was generated using github's API, and probably some other condition...

Anyway the best solution for this is to re-render all blog posts in production. Something I should do, indeed. I'll turn this issue into a task and fix this.
