### ISSUE TITLE
What's the current state of the art javascript build process + spring boot web app integration?

### ISSUE THREAD

**Issue by theonlyguills** [spring-io/sagan#527]
I had a discussion on a RaveJS issue about where things are going on the javascript application front. Basically RaveJS is not there yet and @unscriptable does not have time to really make progress on it anymore. It's not ready to be used for a new project that needs to go to production 'soon'.

Sagan being the RI, I'm now looking at it to structure our future project. Sagan is a couple of years old though, and I'm sure some things have changed in the javascript world (which I don't know as much) since it was created. 

Is this still the best way to integrate a javascript build process with a spring boot web app? Are there things that could be done better now that Sagan doesn't do? Are there better ways to structure the javascript build process?

I'm just trying to see if any improvements could be made now that some time has passed. Maybe it would be useful to have a page / wiki that details things that Sagan could now do better, if any.

**Comment by bclozel** [comment]
Hi @theonlyguills 
Thanks for raising this issue here - you're right about rave and curl.

Sagan is (already!) a couple of years old and it's got a lot of issues in its backlog - but we're still dedicated to maintaining it as a real reference application and it's been running in production since the beginning.

Now I've been trying multiple solutions regarding the client/server build + JavaScript stack + Spring Boot integration. The result of those experiments lives [in the Spring Framework resource handling example app](https://github.com/bclozel/spring-resource-handling/) and in a [dedicated workshop](https://bit.ly/resourcehandling) I've recently given at [Spring I/O](http://www.springio.net/).

Basically I'm thinking about using:

* System.js as a module loader (loads ES6, AMD, CommonJS)
* traceur or babel if some ES6 code makes its way into our codebase
* system.js builder as a packaging/minification solution
* JSPM as a front-end package manager (effectively replacing bower, and more)

Those upcoming changes tell me a couple of things about the current arrangements:

1. separating client/server builds will make this transition easier
1. using modules from the start will also make this quite easy, since system.js supports the format we're using right now
1. since Sagan's inception, multiple maven/gradle plugins make this easier to integrate with your JVM build toolchain
1. [Spring Framework's Resource Handling feature](https://spring.io/blog/2014/07/24/spring-framework-4-1-handling-static-web-resources) is definitely a plus here and should be introduced in Sagan (see #437 ).

Note that the [resource handling workshop](https://bit.ly/resourcehandling) is showing multiple ways to do this - you should adapt this to your use case: is it a single page app? A more traditional web app? Something in between like Sagan?

I've created a couple of issues to track this: #540 and #541
In the meantime, we can discuss this here or in one of the repos I linked here.

**Comment by gregturn** [comment]
@bclozel I've accumulated some experience with using SASS in Gradle-based systems as a nice way to create modular CSS that ends up merged together and even minified. I applied it on our fork of sagan (which is private right now), but would be happy to work on carrying this feedback back to sagan.

**Comment by bclozel** [comment]
@gregturn Interesting - if I had to use a CSS preprocessor, I'd probably go with LESS. Last time I checked, less.js was an interesting alternative for development mode (you don't have to transpile every time you change something, it can be done within the browser).

Other than that, the setup should be fairly similar to what you have.

**Comment by gregturn** [comment]
I steered towards SASS because I use https://github.com/inuitcss/getting-started for lots of projects, and they wrote it in SASS. But as Craig says, anything to move off direct CSS is a boost in developer experience.
