### ISSUE TITLE
Providing svg badges

### ISSUE THREAD

**Issue by mp911de** [spring-io/sagan#637]
Version numbers on `readme.md` pages are a constant source of effort since they require to be updated with every release. Providing dependency sections on the GitHub readme pages is handy for users (as on the spring.io project pages). 

How about adding a service for SVG badges to be referenced within readme files? Badge data would be based on project versions so one could reference latest stable/current snapshot/release train etc.

See http://shields.io/ for examples.

**Comment by bclozel** [comment]
I don't get your point here.
Sagan only provides version information for our own tools (and 3rd party tools), such as start.spring.io, through a REST endpoint (see https://spring.io/project_metadata/spring-data.json).

Any project team can change their project page (`http://projects.spring.io/spring-*`) however they see fit, since it's managed by github pages. If you'd like to see something deployed to all project pages, you can send a PR to [the skeleton project here](https://github.com/spring-projects/gh-pages).

What did you have in mind? Which pages should be updated?

**Comment by mp911de** [comment]
Sorry for confusion. I'm talking about plain Github readme.md files (see https://github.com/spring-projects/spring-data-jpa#quick-start) within the particular Github repos. These are static documents without any logic but allow including images from remote URL's.

**Comment by bclozel** [comment]
Oh, I see.
In that case, Sagan doesn't enforce anything in that space and all projects are free to do whatever they want with their README (markdown/asciidoctor, badges, etc).

On my side, I think this is a neat idea and Sagan could provide such an endpoint easily.

If you have an SVG example, feel free to copy/paste it here! I'm especially wondering about what the text should say. `artifactId | version` ?
With some of our projects, this could lead to `spring-cloud-cloudfoundry | 1.0.0.RELEASE`

What do you think?

**Comment by mp911de** [comment]
Examples: https://github.com/mp911de/lettuce#lettuce---advanced-java-redis-client, http://shields.io/
[![Maven Central](https://img.shields.io/maven-central/v/org.springframework/spring-core.svg)]()

Shields.io has badges for Maven Central but since Sagan has more sophisticated artifact version options, I'd rather go for an own solution. I'll take a look how to contribute that feature and I'd come back with a PR :)
