### ISSUE TITLE
Download button is missing from http://spring.io/tools in Firefox on Linux

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/sagan#694]
The problem is believed to be in [this line](https://github.com/spring-io/sagan/blob/1b92eeb0e84671bf08dfc9f3245aeda456c63365/sagan-client/src/feature/platformDownloads/main.js#L12) where `os.type()` ends up being `Unknown`.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1334817 for all the details.

**Comment by dholbert** [comment]
It's really an issue with these lines:
https://github.com/spring-io/sagan/blob/dc100df311a0aa0b7e09b6aae1ede2f06abcbc9c/sagan-client/src/platform/os.js#L29-L30

That code seems to be expecting that navigator.appVersion will include "Linux" on Linux -- but in Firefox, it happens to have "X11" instead, for arcane historical reasons (and because [appVersion is deprecated as a sniffing API](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/appVersion)).

**Comment by dholbert** [comment]
There are some specific suggested fixes in [this bugzilla comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1334817#c20) -- quoting the key part:
> They could either sniff navigator.userAgent will contains the Linux token:
> `...a.userAgent.indexOf('Linux') !== - 1 ? 'Linux' : f`
>  or modify their Linux sniffing to be something like 
> `...a.appVersion.indexOf('Linux') !== - 1 || a.appVersion.indexOf('X11') : 'Linux' : f`
