### ISSUE TITLE
Spring Cloud docs and version widget not rendered

### ISSUE THREAD

**Issue by dsyer** [spring-io/sagan#700]
The version and documentation chooser used to show on the main spring cloud page but it seems to have disappeared.

**Comment by bclozel** [comment]
You mean [this page](http://projects.spring.io/spring-cloud/)?

This seems to be way behind [the reference repo](https://github.com/spring-projects/gh-pages) (still importing stuff that has been deleted a while ago). The page is displayed correctly on my side with http but not https, this is something that has been fixed a while ago as well in other repositories. It's trying to fetch the project data over http instead of https, causing a security error in the browser.

I've tried to create a PR for this but this seems to share no history with the upstream repo. Pulling from the reference repo does fix things, though.

**Comment by dsyer** [comment]
Thanks Brian. I applied that change and pulled in changes from the upstream repo. Nearly all working now. But the version chooser in the quickstart is borked. I'll have a look and see if I can see why.

**Comment by bclozel** [comment]
Your current page has JavaScript errors.
This commit fixes it all: https://github.com/bclozel/spring-cloud/commit/3fe81abd8286360f08252a50afa1af522fbe9187

Details:
* everything related to zeroclipboard has been removed, and copySnippets.js should not use it anymore
* the projectDocumentationWidget.js should not fetch courses from the pivotal course website (now closed)
