### ISSUE TITLE
View related "guides" in Learn section

### ISSUE THREAD

**Issue by abdoughr** [spring-io/sagan#760]
I WANT to discover guides for a specific project
SO I can quickly start learning about specific objectives

----------------

GIVEN I clicked on the 'learn' tab of a project in the subheader
WHEN I reach the learn section
THEN I see specific guides with title, the first sentence of guide and a link to reach them

**Comment by karinepires** [comment]
@gbufrem On first load (after restarting the app, which means after each deploy of a new feature) it will take time for getting all guides, therefore the project-page takes about 1.2minutes to load.

**Comment by dsyer** [comment]
Sounds like the sort of data that can be pre-computed (so there is always a cached value to fallback on while the new values are being calculated).

**Comment by bclozel** [comment]
@karinepires This is due to #574.

The problem is, guides metadata is stored within the document and shared as global state (I know...), which is a double-bug in itself:
* you have to render a guide to get that metadata; ideally you should get that data when getting the list of guides
* since that state is stored in memory, all application instances should compute all guides to get a full picture; but that's not what we're doing since rendered guides are stored in a shared cache.

You can keep using this method for now and I'll fix this with #574.

**Comment by bclozel** [comment]
We've redesigned the website completely and this issue does not apply anymore.
