### ISSUE TITLE
Default (standalone) profile doesn't work any more

### ISSUE THREAD

**Issue by dsyer** [spring-io/sagan#884]
Running the app locally doesn't work any more since some security patches in Spring Framework - the JS assets cannot be loaded because jspm puts illegal characters in the file paths. To fix this probably requires a re-write of the client app build. Maybe we can fake it in the meantime by switching on the asset pipeline features (minification, cache busting etc) in all profiles?

**Comment by guwan** [comment]
Hasn't it been solved yet?
./gradlew :sagan-site:bootRun
jspm assets  still cannot be loaded .
thank you.

**Comment by guwan** [comment]
There are two ways to solve this problem.

1:replace
assets: ['src/img*/**', 'src/*.txt', 'src/*.html', 'src/font*/**', 'src/css*/filterable-list.css',
    'src/config.js', 'src/jspm_packages*/system*', 'src/jspm_packages*/**/*.ttf', 'src/jspm_packages*/**/*.woff'],
with
assets: ['src/img*/**', 'src/*.txt', 'src/*.html', 'src/font*/**', 'src/css*/filterable-list.css',
    'src/config.js', 'src/jspm_packages*/system*', 'src/jspm_packages*/**/*.ttf', 'src/jspm_packages*/**/*.woff', 'src/jspm_packages*/**'],
in gulpfile.js

or
2.replace
- file:../knos-client/src/
with
- file:knos-client/src/

I recommend the second way.

**Comment by dsyer** [comment]
My comment in #885 suggests that those changes would be unnecessary (not sure what they do anyway).

**Comment by bclozel** [comment]
This behavior is due to the fix in spring-projects/spring-framework#16959. In our case, in dev mode only, we're mixing `"../"` (from the base location) and encoded `"@"` (from the node dependencies) in the request path which is triggering this.

In my experience, IDEs tend to use the the project folder as the working directory by default when running `SiteApplication`, and gradle seems to use the module directory when running `./gradlew :sagan-site:bootRun`. So the relative location in the configuration properties is still a good default in my opinion.

I'm looking at a broader fix in Framework but I must be careful and not reintroduce a security issue.
