### ISSUE TITLE
Updating a version causes the current checkbox to change

### ISSUE THREAD

**Issue by philwebb** [spring-io/sagan#903]
This bug hits us often when releasing Spring Boot. To reproduce:

* Got to "manage projects"
* Edit the existing project
* Edit the version for the current release by changing the last digit (i.e. as if a patch release has happened)
* Click update

The expected behavior is the updated version retains the current checkbox. Unfortunately, this sometimes seems to get lost.

**Comment by wilkinsona** [comment]
I just saw this today when adding a new version rather than editing the existing current version. Specifically, I added 2.4.0-SNAPSHOT to Spring Boot's releases and the current setting for 2.3.0.RELEASE was lost.

**Comment by bclozel** [comment]
Part of the problem has been introduced in the fix for #716. I’ve been working on an important refactoring of the domain model, the database schema and the admin web controller to avoid that.

The problem comes from the fact that the admin form is relying on the ordering of the release elements in a collection and they’re sorted by the accessor and not directly with the ORM. Any update that changes the ordering (marking a release as current orders it first) can result in such issues.
