### ISSUE TITLE
/understanding links all broken

### ISSUE THREAD

**Issue by anno1985** [spring-io/sagan#923]
The page https://spring.io/understanding/tomcat is linked from https://spring.io/guides/gs/securing-web/ and also appears in [search results](https://spring.io/search?q=tomcat), yet the server returns 404 for that URL... :(

**Comment by anno1985** [comment]
Archived page here: https://web.archive.org/web/20190218065039/https://spring.io/understanding/Tomcat
Looks like the page's text is not in this repo (anymore?), though: https://github.com/spring-io/sagan/search?q=Tomcat&unscoped_q=Tomcat

**Comment by dsyer** [comment]
All /understanding links seem to be broken. E.g. see https://github.com/spring-guides/gs-rest-hateoas/issues/24.

**Comment by dsyer** [comment]
Looks like it broke here probably: 394a9f0922e

**Comment by dsyer** [comment]
The link from the security guide is no longer there. We have a policy of removing the links, rather than fixing them. It's a shame about the search results, but those pages really have very, very low traffic, so we don't think it will hurt to remove them (it took 6 months before we got the first bug report).

**Comment by dsyer** [comment]
Re-opening while we actually fix some of the links.

**Comment by bclozel** [comment]
Fixed by 9470f07a6b5d8b
